// ============================================================
// DeVuelta — Program Templates by Business Type
// ============================================================

import type { ProgramTemplate } from '@/lib/types';

export const programTemplates: ProgramTemplate[] = [
  {
    businessType: 'cafeteria',
    name: 'Café de Vuelta',
    description: 'Recompensa a tus clientes frecuentes con una bebida gratis después de cada 5 visitas.',
    programType: 'visits',
    goalValue: 5,
    rewardType: 'free_item',
    rewardDetail: 'Bebida gratis',
    passBgColor: '#1a1a2e',
    passTextColor: '#f0e6d3',
    icon: 'Coffee',
    welcomeMessage: '¡Bienvenido! Cada visita te acerca más a tu café gratis. ☕',
  },
  {
    businessType: 'barberia',
    name: 'Corte Frecuente',
    description: 'Dale a tus clientes un descuento especial después de 4 cortes.',
    programType: 'visits',
    goalValue: 4,
    rewardType: 'discount_percent',
    rewardDetail: '30% de descuento en tu próximo corte',
    passBgColor: '#0f172a',
    passTextColor: '#e2e8f0',
    icon: 'Scissors',
    welcomeMessage: '¡Bienvenido! Por cada 4 cortes, el siguiente tiene 30% de descuento. ✂️',
  },
  {
    businessType: 'spa',
    name: 'Bienestar Premium',
    description: 'Acumula puntos con cada servicio y canjea un tratamiento facial de regalo.',
    programType: 'points',
    goalValue: 500,
    rewardType: 'free_item',
    rewardDetail: 'Tratamiento facial de regalo',
    passBgColor: '#1e1b2e',
    passTextColor: '#d4c5f9',
    icon: 'Sparkles',
    welcomeMessage: '¡Bienvenida! Acumula puntos con cada visita y disfruta de un tratamiento especial. ✨',
  },
  {
    businessType: 'restaurante',
    name: 'Mesa Favorita',
    description: 'Cada 8 visitas, invita el postre de tu elección.',
    programType: 'visits',
    goalValue: 8,
    rewardType: 'free_item',
    rewardDetail: 'Postre de regalo',
    passBgColor: '#1a0f0a',
    passTextColor: '#f5deb3',
    icon: 'UtensilsCrossed',
    welcomeMessage: '¡Bienvenido a la familia! Cada 8 visitas, el postre va por nuestra cuenta. 🍰',
  },
  {
    businessType: 'panaderia',
    name: 'Pan de Cada Día',
    description: '6 visitas y llévate una caja de pan artesanal gratis.',
    programType: 'visits',
    goalValue: 6,
    rewardType: 'free_item',
    rewardDetail: 'Caja de pan artesanal gratis',
    passBgColor: '#2d1b0e',
    passTextColor: '#f5e6d3',
    icon: 'Croissant',
    welcomeMessage: '¡Bienvenido! Cada 6 visitas, una caja de pan va por nuestra cuenta. 🥐',
  },
  {
    businessType: 'fitness',
    name: 'Rutina Ganadora',
    description: 'Completa 10 sesiones y obtén una clase gratis.',
    programType: 'visits',
    goalValue: 10,
    rewardType: 'free_item',
    rewardDetail: 'Clase gratis',
    passBgColor: '#0a0f1a',
    passTextColor: '#7dd3fc',
    icon: 'Dumbbell',
    welcomeMessage: '¡Vamos! Cada 10 sesiones, una clase va por nuestra cuenta. 💪',
  },
  {
    businessType: 'tienda',
    name: 'Puntos VIP',
    description: 'Acumula 1 punto por cada $10 gastados. 300 puntos = $100 de descuento.',
    programType: 'points',
    goalValue: 300,
    rewardType: 'discount_fixed',
    rewardDetail: '$100 MXN de descuento',
    passBgColor: '#0f0f1a',
    passTextColor: '#a5b4fc',
    icon: 'ShoppingBag',
    welcomeMessage: '¡Bienvenido al club VIP! Acumula puntos con cada compra. 🛍️',
  },
  {
    businessType: 'veterinaria',
    name: 'Huella Fiel',
    description: 'Cada 5 consultas, el baño de tu mascota es gratis.',
    programType: 'visits',
    goalValue: 5,
    rewardType: 'free_item',
    rewardDetail: 'Baño para tu mascota gratis',
    passBgColor: '#0f1a14',
    passTextColor: '#86efac',
    icon: 'PawPrint',
    welcomeMessage: '¡Bienvenido! Tu mascota se merece lo mejor. Cada 5 visitas, un baño gratis. 🐾',
  },
];

export function getTemplateForBusinessType(type: string): ProgramTemplate | undefined {
  return programTemplates.find((t: ProgramTemplate) => t.businessType === type);
}
